name: Release

on:
  push:
    branches:
      - release

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-freebsd
            cross: true
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            cross: true
          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl
            cross: true
          - os-name: Linux-riscv64
            runs-on: ubuntu-24.04
            target: riscv64gc-unknown-linux-gnu
            cross: true
          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
            cross: false
          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
            cross: false

    runs-on: ${{ matrix.platform.runs-on }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Install cross-compilation dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pkg-config \
            libssl-dev
          
          # Install target-specific dependencies
          case "${{ matrix.platform.target }}" in
            "riscv64gc-unknown-linux-gnu")
              sudo apt-get install -y --no-install-recommends \
                gcc-riscv64-linux-gnu \
                g++-riscv64-linux-gnu \
                libc6-dev-riscv64-cross \
                libssl-dev:riscv64
              echo "OPENSSL_DIR=/usr/lib/riscv64-linux-gnu" >> $GITHUB_ENV
              echo "OPENSSL_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
              echo "PKG_CONFIG_PATH=/usr/lib/riscv64-linux-gnu/pkgconfig" >> $GITHUB_ENV
              ;;
            "aarch64-unknown-linux-musl")
              sudo apt-get install -y --no-install-recommends \
                gcc-aarch64-linux-gnu \
                g++-aarch64-linux-gnu \
                libc6-dev-arm64-cross \
                libssl-dev:arm64
              echo "OPENSSL_DIR=/usr/lib/aarch64-linux-gnu" >> $GITHUB_ENV
              echo "OPENSSL_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
              echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig" >> $GITHUB_ENV
              ;;
            "x86_64-unknown-linux-musl")
              sudo apt-get install -y --no-install-recommends \
                musl-tools \
                libssl-dev
              echo "OPENSSL_DIR=/usr" >> $GITHUB_ENV
              echo "OPENSSL_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
              ;;
            "x86_64-unknown-freebsd")
              sudo apt-get install -y --no-install-recommends \
                libssl-dev
              echo "OPENSSL_DIR=/usr" >> $GITHUB_ENV
              echo "OPENSSL_INCLUDE_DIR=/usr/include" >> $GITHUB_ENV
              ;;
          esac

      - name: Install OpenSSL (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install openssl@3
          echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV

      - name: Install OpenSSL (Windows)
        if: runner.os == 'Windows'
        run: |
          vcpkg install openssl:x64-windows-static
          echo "OPENSSL_DIR=$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows-static" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "OPENSSL_STATIC=1" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.platform.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Generate Cargo.lock
        run: cargo generate-lockfile

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true

      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: ubi
          target: ${{ matrix.platform.target }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
